apiVersion: v1
kind: Secret
metadata:
  name: yelp-backend-secrets
  namespace: yelp-lab2
type: Opaque
stringData:
  MONGODB_URI: "mongodb://mongodb:27017/yelp_db"
  SECRET_KEY: "change-me-in-production"
