apiVersion: v1
kind: ConfigMap
metadata:
  name: yelp-backend-config
  namespace: yelp-lab2
data:
  MONGODB_DB_NAME: "yelp_db"
  ALGORITHM: "HS256"
  ACCESS_TOKEN_EXPIRE_MINUTES: "30"
  GEMINI_API_KEY: ""
  TAVILY_API_KEY: ""
